### ISSUE TITLE
Crash with Optifine

### ISSUE THREAD

**Issue by liuseniubi** [JLChnToZ/MCCustomSkinLoader#142]
> [19一月2021 22:54:39.061] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, Six_color, --version, 1.16.4, --gameDir, C:\Users\37239\Desktop\CREATE\客户端\.minecraft, --assetsDir, C:\Users\37239\Desktop\CREATE\客户端\.minecraft\assets, --assetIndex, 1.16, --uuid, b1d10e9ec6b848f3a4398ef67e729516, --accessToken, ????????, --userType, Mojang, --versionType, PCL2, --width, 854, --height, 480, --launchTarget, fmlclient, --fml.forgeVersion, 35.1.37, --fml.mcVersion, 1.16.4, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20201102.104115, --tweakClass, optifine.OptiFineForgeTweaker]
[19一月2021 22:54:39.070] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher 8.0.9+86+master.3cf110c starting: java version 1.8.0_271 by Oracle Corporation
[19一月2021 22:54:39.403] [main/INFO] [optifine.OptiFineTransformationService/]: OptiFineTransformationService.onLoad
[19一月2021 22:54:39.405] [main/INFO] [optifine.OptiFineTransformationService/]: OptiFine ZIP file: C:\Users\37239\Desktop\CREATE\客户端\.minecraft\libraries\optifine\OptiFine\1.16.4_HD_U_G6\OptiFine-1.16.4_HD_U_G6.jar
[19一月2021 22:54:39.410] [main/INFO] [optifine.OptiFineTransformer/]: Target.PRE_CLASS is available
[19一月2021 22:54:40.454] [main/INFO] [net.minecraftforge.fml.loading.FixSSL/CORE]: Added Lets Encrypt root certificates as additional trust
[19一月2021 22:54:40.527] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/C:/Users/37239/Desktop/CREATE/%e5%ae%a2%e6%88%b7%e7%ab%af/.minecraft/libraries/org/spongepowered/mixin/0.8.2/mixin-0.8.2.jar Service=ModLauncher Env=CLIENT
[19一月2021 22:54:40.543] [main/INFO] [optifine.OptiFineTransformationService/]: OptiFineTransformationService.initialize
[19一月2021 22:54:44.001] [main/INFO] [optifine.OptiFineTransformationService/]: OptiFineTransformationService.transformers
[19一月2021 22:54:44.030] [main/INFO] [optifine.OptiFineTransformer/]: Targets: 305
[19一月2021 22:54:48.295] [main/INFO] [optifine.OptiFineTransformationService/]: additionalClassesLocator: [optifine., net.optifine.]
[19一月2021 22:54:48.557] [main/INFO] [mixin/]: Successfully loaded Mixin Connector [com.performant.coremod.mixin.Connector]
[19一月2021 22:54:48.568] [main/INFO] [cpw.mods.modlauncher.LaunchServiceHandler/MODLAUNCHER]: Launching target 'fmlclient' with arguments [--version, 1.16.4, --gameDir, C:\Users\37239\Desktop\CREATE\客户端\.minecraft, --assetsDir, C:\Users\37239\Desktop\CREATE\客户端\.minecraft\assets, --uuid, b1d10e9ec6b848f3a4398ef67e729516, --username, Six_color, --assetIndex, 1.16, --accessToken, ????????, --userType, Mojang, --versionType, PCL2, --width, 854, --height, 480, --tweakClass, optifine.OptiFineForgeTweaker]
[19一月2021 22:54:48.766] [main/INFO] [com.performant.coremod.Performant/]: Performant configs loaded
[19一月2021 22:54:49.806] [main/INFO] [com.performant.coremod.Performant/]: Not enabling mixin forcom.performant.coremod.mixin.forge.BasicEventHooksMixin as config disables it.
[19一月2021 22:54:49.861] [main/INFO] [com.performant.coremod.Performant/]: Not enabling mixin forcom.performant.coremod.mixin.entity.LivingEntityUpdateEventMixin as config disables it.
[19一月2021 22:54:50.209] [main/WARN] [mixin/]: @Mixin target net/minecraft/world/server/ChunkManager$EntityTracker is public in performant.mixins.json:world.chunk.ChunkManagerEntityTrackMixin and should be specified in value
[19一月2021 22:54:51.130] [main/INFO] [STDOUT/]: [net.minecraft.client.main.Main:main:80]: Completely ignored arguments: [--tweakClass, optifine.OptiFineForgeTweaker]
[19一月2021 22:54:54.061] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
[19一月2021 22:54:54.062] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:39)
[19一月2021 22:54:54.062] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
[19一月2021 22:54:54.062] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
[19一月2021 22:54:54.062] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
[19一月2021 22:54:54.063] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
[19一月2021 22:54:54.063] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: Caused by: java.lang.reflect.InvocationTargetException
[19一月2021 22:54:54.063] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[19一月2021 22:54:54.063] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[19一月2021 22:54:54.063] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[19一月2021 22:54:54.063] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[19一月2021 22:54:54.063] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
[19一月2021 22:54:54.064] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
[19一月2021 22:54:54.064] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	... 4 more
[19一月2021 22:54:54.064] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: Caused by: java.lang.NoClassDefFoundError: Lnet/minecraft/client/resources/SkinManager;
[19一月2021 22:54:54.064] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at java.lang.Class.getDeclaredFields0(Native Method)
[19一月2021 22:54:54.064] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at java.lang.Class.privateGetDeclaredFields(Unknown Source)
[19一月2021 22:54:54.064] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at java.lang.Class.getDeclaredFields(Unknown Source)
[19一月2021 22:54:54.065] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at net.optifine.reflect.FieldLocatorTypes.<init>(FieldLocatorTypes.java:25)
[19一月2021 22:54:54.065] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at net.optifine.reflect.Reflector.<clinit>(Reflector.java:495)
[19一月2021 22:54:54.065] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at net.minecraft.crash.CrashReport.func_71504_g(CrashReport.java:101)
[19一月2021 22:54:54.065] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at net.minecraft.crash.CrashReport.<init>(CrashReport.java:54)
[19一月2021 22:54:54.065] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at net.minecraft.crash.CrashReport.func_230188_h_(CrashReport.java:425)
[19一月2021 22:54:54.065] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at net.minecraft.client.main.Main.main(Main.java:122)
[19一月2021 22:54:54.065] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	... 10 more
[19一月2021 22:54:54.066] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: Caused by: java.lang.ClassNotFoundException: net.minecraft.client.resources.SkinManager
[19一月2021 22:54:54.066] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at java.lang.ClassLoader.findClass(Unknown Source)
[19一月2021 22:54:54.066] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[19一月2021 22:54:54.067] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:106)
[19一月2021 22:54:54.067] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[19一月2021 22:54:54.067] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	... 19 more
[19一月2021 22:54:54.068] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:-1]: 	Suppressed: java.lang.SecurityException: class "net.minecraft.client.resources.SkinManager"'s signer information does not match signer information of other classes in the same package
[19一月2021 22:54:54.068] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:-1]: 		at java.lang.ClassLoader.checkCerts(Unknown Source)
[19一月2021 22:54:54.068] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:-1]: 		at java.lang.ClassLoader.preDefineClass(Unknown Source)
[19一月2021 22:54:54.068] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:-1]: 		at java.lang.ClassLoader.defineClass(Unknown Source)
[19一月2021 22:54:54.068] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:-1]: 		at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:138)
[19一月2021 22:54:54.068] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:-1]: 		at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98)
[19一月2021 22:54:54.069] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:-1]: 		... 20 more

```

**Comment by ZekerZhayard** [comment]
你的 CSL 版本太旧了，用新版 https://csl.littleservice.cn/mods/CustomSkinLoader_Forge-14.13-SNAPSHOT-214.jar
