### ISSUE TITLE
[1.16.4]装mod无法进入游戏

### ISSUE THREAD

**Issue by Luorons** [JLChnToZ/MCCustomSkinLoader#144]
Command: "C:\\Program Files\\Java\\jre1.8.0_261\\bin\\java.exe" -Dminecraft.client.jar=.minecraft\versions\1.16.4\1.16.4.jar -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -Xmn128m -Xmx4096m -Dfml.ignoreInvalidMinecraftCertificates=true -Dfml.ignorePatchDiscrepancies=true -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump "-Djava.library.path=E:\\minecraft 1.16.5\\.minecraft\\versions\\1.16.4\\natives" -Dminecraft.launcher.brand=HMCL -Dminecraft.launcher.version=3.3.172 -cp "E:\\minecraft 1.16.5\\.minecraft\\libraries\\net\\minecraftforge\\forge\\1.16.4-35.1.37\\forge-1.16.4-35.1.37.jar;E:\\minecraft 1.16.5\\.minecraft\\libraries\\org\\ow2\\asm\\asm\\9.0\\asm-9.0.jar;E:\\minecraft 1.16.5\\.minecraft\\libraries\\org\\ow2\\asm\\asm-commons\\9.0\\asm-commons-9.0.jar;E:\\minecraft 1.16.5\\.minecraft\\libraries\\org\\ow2\\asm\\asm-tree\\9.0\\asm-tree-9.0.jar;E:\\minecraft 1.16.5\\.minecraft\\libraries\\org\\ow2\\asm\\asm-util\\9.0\\asm-util-9.0.jar;E:\\minecraft 1.16.5\\.minecraft\\libraries\\org\\ow2\\asm\\asm-analysis\\9.0\\asm-analysis-9.0.jar;E:\\minecraft 1.16.5\\.minecraft\\libraries\\cpw\\mods\\modlauncher\\8.0.9\\modlauncher-8.0.9.jar;E:\\minecraft 1.16.5\\.minecraft\\libraries\\cpw\\mods\\grossjava9hacks\\1.3.0\\grossjava9hacks-1.3.0.jar;E:\\minecraft 1.16.5\\.minecraft\\libraries\\net\\minecraftforge\\accesstransformers\\3.0.1\\accesstransformers-3.0.1.jar;E:\\minecraft 1.16.5\\.minecraft\\libraries\\org\\antlr\\antlr4-runtime\\4.9.1\\antlr4-runtime-4.9.1.jar;E:\\minecraft 1.16.5\\.minecraft\\libraries\\net\\minecraftforge\\eventbus\\4.0.0\\eventbus-4.0.0.jar;E:\\minecraft 1.16.5\\.minecraft\\libraries\\net\\minecraftforge\\forgespi\\3.2.0\\forgespi-3.2.0.jar;E:\\minecraft 1.16.5\\.minecraft\\libraries\\net\\minecraftforge\\coremods\\4.0.3\\coremods-4.0.3.jar;E:\\minecraft 1.16.5\\.minecraft\\libraries\\net\\minecraftforge\\unsafe\\0.2.0\\unsafe-0.2.0.jar;E:\\minecraft 1.16.5\\.minecraft\\libraries\\com\\electronwill\\night-config\\core\\3.6.2\\core-3.6.2.jar;E:\\minecraft 1.16.5\\.minecraft\\libraries\\com\\electronwill\\night-config\\toml\\3.6.2\\toml-3.6.2.jar;E:\\minecraft 1.16.5\\.minecraft\\libraries\\org\\jline\\jline\\3.12.1\\jline-3.12.1.jar;E:\\minecraft 1.16.5\\.minecraft\\libraries\\org\\apache\\maven\\maven-artifact\\3.6.0\\maven-artifact-3.6.0.jar;E:\\minecraft 1.16.5\\.minecraft\\libraries\\net\\jodah\\typetools\\0.8.3\\typetools-0.8.3.jar;E:\\minecraft 1.16.5\\.minecraft\\libraries\\org\\apache\\logging\\log4j\\log4j-api\\2.11.2\\log4j-api-2.11.2.jar;E:\\minecraft 1.16.5\\.minecraft\\libraries\\org\\apache\\logging\\log4j\\log4j-core\\2.11.2\\log4j-core-2.11.2.jar;E:\\minecraft 1.16.5\\.minecraft\\libraries\\net\\minecrell\\terminalconsoleappender\\1.2.0\\terminalconsoleappender-1.2.0.jar;E:\\minecraft 1.16.5\\.minecraft\\libraries\\net\\sf\\jopt-simple\\jopt-simple\\5.0.4\\jopt-simple-5.0.4.jar;E:\\minecraft 1.16.5\\.minecraft\\libraries\\org\\spongepowered\\mixin\\0.8.2\\mixin-0.8.2.jar;E:\\minecraft 1.16.5\\.minecraft\\libraries\\net\\minecraftforge\\nashorn-core-compat\\15.1.1\\nashorn-core-compat-15.1.1.jar;E:\\minecraft 1.16.5\\.minecraft\\libraries\\com\\mojang\\patchy\\1.1\\patchy-1.1.jar;E:\\minecraft 1.16.5\\.minecraft\\libraries\\oshi-project\\oshi-core\\1.1\\oshi-core-1.1.jar;E:\\minecraft 1.16.5\\.minecraft\\libraries\\net\\java\\dev\\jna\\jna\\4.4.0\\jna-4.4.0.jar;E:\\minecraft 1.16.5\\.minecraft\\libraries\\net\\java\\dev\\jna\\platform\\3.4.0\\platform-3.4.0.jar;E:\\minecraft 1.16.5\\.minecraft\\libraries\\com\\ibm\\icu\\icu4j\\66.1\\icu4j-66.1.jar;E:\\minecraft 1.16.5\\.minecraft\\libraries\\com\\mojang\\javabridge\\1.0.22\\javabridge-1.0.22.jar;E:\\minecraft 1.16.5\\.minecraft\\libraries\\io\\netty\\netty-all\\4.1.25.Final\\netty-all-4.1.25.Final.jar;E:\\minecraft 1.16.5\\.minecraft\\libraries\\com\\google\\guava\\guava\\21.0\\guava-21.0.jar;E:\\minecraft 1.16.5\\.minecraft\\libraries\\org\\apache\\commons\\commons-lang3\\3.5\\commons-lang3-3.5.jar;E:\\minecraft 1.16.5\\.minecraft\\libraries\\commons-io\\commons-io\\2.5\\commons-io-2.5.jar;E:\\minecraft 1.16.5\\.minecraft\\libraries\\commons-codec\\commons-codec\\1.10\\commons-codec-1.10.jar;E:\\minecraft 1.16.5\\.minecraft\\libraries\\net\\java\\jinput\\jinput\\2.0.5\\jinput-2.0.5.jar;E:\\minecraft 1.16.5\\.minecraft\\libraries\\net\\java\\jutils\\jutils\\1.0.0\\jutils-1.0.0.jar;E:\\minecraft 1.16.5\\.minecraft\\libraries\\com\\mojang\\brigadier\\1.0.17\\brigadier-1.0.17.jar;E:\\minecraft 1.16.5\\.minecraft\\libraries\\com\\mojang\\datafixerupper\\4.0.26\\datafixerupper-4.0.26.jar;E:\\minecraft 1.16.5\\.minecraft\\libraries\\com\\google\\code\\gson\\gson\\2.8.0\\gson-2.8.0.jar;E:\\minecraft 1.16.5\\.minecraft\\libraries\\com\\mojang\\authlib\\2.1.28\\authlib-2.1.28.jar;E:\\minecraft 1.16.5\\.minecraft\\libraries\\org\\apache\\commons\\commons-compress\\1.8.1\\commons-compress-1.8.1.jar;E:\\minecraft 1.16.5\\.minecraft\\libraries\\org\\apache\\httpcomponents\\httpclient\\4.3.3\\httpclient-4.3.3.jar;E:\\minecraft 1.16.5\\.minecraft\\libraries\\commons-logging\\commons-logging\\1.1.3\\commons-logging-1.1.3.jar;E:\\minecraft 1.16.5\\.minecraft\\libraries\\org\\apache\\httpcomponents\\httpcore\\4.3.2\\httpcore-4.3.2.jar;E:\\minecraft 1.16.5\\.minecraft\\libraries\\it\\unimi\\dsi\\fastutil\\8.2.1\\fastutil-8.2.1.jar;E:\\minecraft 1.16.5\\.minecraft\\libraries\\org\\lwjgl\\lwjgl\\3.2.2\\lwjgl-3.2.2.jar;E:\\minecraft 1.16.5\\.minecraft\\libraries\\org\\lwjgl\\lwjgl-jemalloc\\3.2.2\\lwjgl-jemalloc-3.2.2.jar;E:\\minecraft 1.16.5\\.minecraft\\libraries\\org\\lwjgl\\lwjgl-openal\\3.2.2\\lwjgl-openal-3.2.2.jar;E:\\minecraft 1.16.5\\.minecraft\\libraries\\org\\lwjgl\\lwjgl-opengl\\3.2.2\\lwjgl-opengl-3.2.2.jar;E:\\minecraft 1.16.5\\.minecraft\\libraries\\org\\lwjgl\\lwjgl-glfw\\3.2.2\\lwjgl-glfw-3.2.2.jar;E:\\minecraft 1.16.5\\.minecraft\\libraries\\org\\lwjgl\\lwjgl-stb\\3.2.2\\lwjgl-stb-3.2.2.jar;E:\\minecraft 1.16.5\\.minecraft\\libraries\\org\\lwjgl\\lwjgl-tinyfd\\3.2.2\\lwjgl-tinyfd-3.2.2.jar;E:\\minecraft 1.16.5\\.minecraft\\libraries\\com\\mojang\\text2speech\\1.11.3\\text2speech-1.11.3.jar;E:\\minecraft 1.16.5\\.minecraft\\libraries\\org\\jackhuang\\hmcl\\transformer-discovery-service\\1.0\\transformer-discovery-service-1.0.jar;E:\\minecraft 1.16.5\\.minecraft\\versions\\1.16.4\\1.16.4.jar" "-Dhmcl.transformer.candidates=E:\\minecraft 1.16.5\\.minecraft\\libraries/optifine/OptiFine/1.16.4_HD_U_G6/OptiFine-1.16.4_HD_U_G6.jar" cpw.mods.modlauncher.Launcher --username jinjinjin --version "HMCL 3.3.172" --gameDir "E:\\minecraft 1.16.5\\.minecraft" --assetsDir "E:\\minecraft 1.16.5\\.minecraft\\assets" --assetIndex 1.16 --uuid 33d96f88dcb335c1b23cccc63bcd652b --accessToken 057c7a6948c7481c95f51eb5630ebe20 --userType mojang --versionType "HMCL 3.3.172" --width 854 --height 480 --tweakClass optifine.OptiFineTweaker --launchTarget fmlclient --fml.forgeVersion 35.1.37 --fml.mcVersion 1.16.4 --fml.forgeGroup net.minecraftforge --fml.mcpVersion 20201102.104115
2021-02-19 09:20:04,422 main WARN Advanced terminal features are not available in this environment
[09:20:04] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, <player>, --version, HMCL 3.3.172, --gameDir, E:\minecraft 1.16.5\.minecraft, --assetsDir, E:\minecraft 1.16.5\.minecraft\assets, --assetIndex, 1.16, --uuid, <uuid>, --accessToken, ????????, --userType, mojang, --versionType, HMCL 3.3.172, --width, 854, --height, 480, --tweakClass, optifine.OptiFineTweaker, --launchTarget, fmlclient, --fml.forgeVersion, 35.1.37, --fml.mcVersion, 1.16.4, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20201102.104115]
[09:20:04] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 8.0.9+86+master.3cf110c starting: java version 1.8.0_261 by Oracle Corporation
[09:20:04] [main/INFO] [op.OptiFineTransformationService/]: OptiFineTransformationService.onLoad
[09:20:04] [main/INFO] [op.OptiFineTransformationService/]: OptiFine ZIP file: E:\minecraft 1.16.5\.minecraft\libraries\optifine\OptiFine\1.16.4_HD_U_G6\OptiFine-1.16.4_HD_U_G6.jar
[09:20:04] [main/INFO] [op.OptiFineTransformer/]: Target.PRE_CLASS is available
[09:20:04] [main/INFO] [ne.mi.fm.lo.FixSSL/CORE]: Added Lets Encrypt root certificates as additional trust
[09:20:04] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/E:/minecraft%201.16.5/.minecraft/libraries/org/spongepowered/mixin/0.8.2/mixin-0.8.2.jar Service=ModLauncher Env=CLIENT
[09:20:04] [main/INFO] [op.OptiFineTransformationService/]: OptiFineTransformationService.initialize
[09:20:05] [main/INFO] [op.OptiFineTransformationService/]: OptiFineTransformationService.transformers
[09:20:05] [main/INFO] [op.OptiFineTransformer/]: Targets: 305
[09:20:06] [main/INFO] [op.OptiFineTransformationService/]: additionalClassesLocator: [optifine., net.optifine.]
[09:20:06] [main/INFO] [cp.mo.mo.LaunchServiceHandler/MODLAUNCHER]: Launching target 'fmlclient' with arguments [--version, HMCL 3.3.172, --gameDir, E:\minecraft 1.16.5\.minecraft, --assetsDir, E:\minecraft 1.16.5\.minecraft\assets, --uuid, <uuid>, --username, <player>, --assetIndex, 1.16, --accessToken, ????????, --userType, mojang, --versionType, HMCL 3.3.172, --width, 854, --height, 480, --tweakClass, optifine.OptiFineTweaker]
[09:20:06] [main/INFO] [STDOUT/]: [net.minecraft.client.main.Main:main:80]: Completely ignored arguments: [--tweakClass, optifine.OptiFineTweaker]
[09:20:06] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
[09:20:06] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:39)
[09:20:06] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
[09:20:06] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
[09:20:06] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
[09:20:06] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
[09:20:06] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: Caused by: java.lang.reflect.InvocationTargetException
[09:20:06] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[09:20:06] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[09:20:06] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[09:20:06] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[09:20:06] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
[09:20:06] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
[09:20:06] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	... 4 more
[09:20:06] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: Caused by: java.lang.NoClassDefFoundError: Lnet/minecraft/client/resources/SkinManager;
[09:20:06] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at java.lang.Class.getDeclaredFields0(Native Method)
[09:20:06] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at java.lang.Class.privateGetDeclaredFields(Unknown Source)
[09:20:06] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at java.lang.Class.getDeclaredFields(Unknown Source)
[09:20:06] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at net.optifine.reflect.FieldLocatorTypes.<init>(FieldLocatorTypes.java:25)
[09:20:06] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at net.optifine.reflect.Reflector.<clinit>(Reflector.java:495)
[09:20:06] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at net.minecraft.crash.CrashReport.func_71504_g(CrashReport.java:101)
[09:20:06] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at net.minecraft.crash.CrashReport.<init>(CrashReport.java:54)
[09:20:06] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at net.minecraft.crash.CrashReport.func_230188_h_(CrashReport.java:425)
[09:20:06] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at net.minecraft.client.main.Main.main(Main.java:122)
[09:20:06] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	... 10 more
[09:20:06] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: Caused by: java.lang.ClassNotFoundException: net.minecraft.client.resources.SkinManager
[09:20:06] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at java.lang.ClassLoader.findClass(Unknown Source)
[09:20:06] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[09:20:06] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:106)
[09:20:06] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[09:20:06] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	... 19 more
[09:20:06] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:-1]: 	Suppressed: java.lang.SecurityException: class "net.minecraft.client.resources.SkinManager"'s signer information does not match signer information of other classes in the same package
[09:20:06] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:-1]: 		at java.lang.ClassLoader.checkCerts(Unknown Source)
[09:20:06] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:-1]: 		at java.lang.ClassLoader.preDefineClass(Unknown Source)
[09:20:06] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:-1]: 		at java.lang.ClassLoader.defineClass(Unknown Source)
[09:20:06] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:-1]: 		at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:138)
[09:20:06] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:-1]: 		at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98)
[09:20:06] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:-1]: 		... 20 more
Exception in thread "main" 

**版本降到1.16.2后就无此现象。
（PS：单独装了此mod，forge版本是35.1.37）**

**Comment by ZekerZhayard** [comment]
你的csl版本太老了，用最新的 https://csl.littleservice.cn/mods/CustomSkinLoader_Forge-14.13-SNAPSHOT-218.jar
