### ISSUE TITLE
Add Support For The Mod: ESSENTIAL

### ISSUE THREAD

**Issue by PolyframeX** [JLChnToZ/MCCustomSkinLoader#227]
When using Essential, Skins do not load correctly, and display incorrectly. This is a compatibility issue.

**Comment by ZekerZhayard** [comment]
can you provide any logs?

**Comment by PolyframeX** [comment]
Here is the latest.log with just booting up the game, generating a world, and loading into it.

[05:14:32] [main/INFO]: ModLauncher running: args [--username, PolyframeX, --version, forge-43.1.52, --gameDir, C:\Users\Court\curseforge\minecraft\Instances\B, --assetsDir, C:\Users\Court\curseforge\minecraft\Install\assets, --assetIndex, 1.19, --uuid, 56a59019c28a4115aa8cbfedc7875161, --accessToken, ????????, --clientId, YjBlMDY5MWYtNDY3NS00YmExLTg5N2EtMzFiOTc4MjY2Njgx, --xuid, 2535471871105373, --userType, msa, --versionType, release, --width, 1024, --height, 768, --launchTarget, forgeclient, --fml.forgeVersion, 43.1.52, --fml.mcVersion, 1.19.2, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20220805.130853]
[05:14:32] [main/INFO]: ModLauncher 10.0.8+10.0.8+main.0ef7e830 starting: java version 17.0.3 by Microsoft; OS Windows 10 arch amd64 version 10.0
[05:14:32] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/C:/Users/Court/curseforge/minecraft/Install/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%2391!/ Service=ModLauncher Env=CLIENT
[05:14:33] [main/INFO]: Found mod file CustomSkinLoader_ForgeActive-14.14.jar of type MOD with provider {mods folder locator at C:\Users\Court\curseforge\minecraft\Instances\B\mods}
[05:14:33] [main/WARN]: Mod file C:\Users\Court\curseforge\minecraft\Install\libraries\net\minecraftforge\fmlcore\1.19.2-43.1.52\fmlcore-1.19.2-43.1.52.jar is missing mods.toml file
[05:14:33] [main/WARN]: Mod file C:\Users\Court\curseforge\minecraft\Install\libraries\net\minecraftforge\javafmllanguage\1.19.2-43.1.52\javafmllanguage-1.19.2-43.1.52.jar is missing mods.toml file
[05:14:33] [main/WARN]: Mod file C:\Users\Court\curseforge\minecraft\Install\libraries\net\minecraftforge\lowcodelanguage\1.19.2-43.1.52\lowcodelanguage-1.19.2-43.1.52.jar is missing mods.toml file
[05:14:33] [main/WARN]: Mod file C:\Users\Court\curseforge\minecraft\Install\libraries\net\minecraftforge\mclanguage\1.19.2-43.1.52\mclanguage-1.19.2-43.1.52.jar is missing mods.toml file
[05:14:33] [main/INFO]: Found mod file fmlcore-1.19.2-43.1.52.jar of type LIBRARY with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@3f49e266
[05:14:33] [main/INFO]: Found mod file javafmllanguage-1.19.2-43.1.52.jar of type LANGPROVIDER with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@3f49e266
[05:14:33] [main/INFO]: Found mod file lowcodelanguage-1.19.2-43.1.52.jar of type LANGPROVIDER with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@3f49e266
[05:14:33] [main/INFO]: Found mod file mclanguage-1.19.2-43.1.52.jar of type LANGPROVIDER with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@3f49e266
[05:14:33] [main/INFO]: Found mod file client-1.19.2-20220805.130853-srg.jar of type MOD with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@3f49e266
[05:14:33] [main/INFO]: Found mod file forge-1.19.2-43.1.52-universal.jar of type MOD with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@3f49e266
[05:14:33] [main/INFO]: No dependencies to load found. Skipping!
[05:14:34] [main/INFO]: Launching target 'forgeclient' with arguments [--version, forge-43.1.52, --gameDir, C:\Users\Court\curseforge\minecraft\Instances\B, --assetsDir, C:\Users\Court\curseforge\minecraft\Install\assets, --uuid, 56a59019c28a4115aa8cbfedc7875161, --username, PolyframeX, --assetIndex, 1.19, --accessToken, ????????, --clientId, YjBlMDY5MWYtNDY3NS00YmExLTg5N2EtMzFiOTc4MjY2Njgx, --xuid, 2535471871105373, --userType, msa, --versionType, release, --width, 1024, --height, 768]
[05:14:39] [pool-3-thread-1/INFO]: Building unoptimized datafixer
[05:14:41] [Render thread/WARN]: Assets URL 'union:/C:/Users/Court/curseforge/minecraft/Install/libraries/net/minecraft/client/1.19.2-20220805.130853/client-1.19.2-20220805.130853-srg.jar%23149!/assets/.mcassetsroot' uses unexpected schema
[05:14:41] [Render thread/WARN]: Assets URL 'union:/C:/Users/Court/curseforge/minecraft/Install/libraries/net/minecraft/client/1.19.2-20220805.130853/client-1.19.2-20220805.130853-srg.jar%23149!/data/.mcassetsroot' uses unexpected schema
[05:14:41] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[05:14:41] [Render thread/INFO]: Setting user: PolyframeX
[05:14:41] [Render thread/INFO]: Using Default JreDnsResolver
[05:14:42] [Render thread/INFO]: OptiFine not detected.
[05:14:42] [Render thread/INFO]: Starting DI!
[05:14:42] [Render thread/INFO]: Backend library: LWJGL version 3.3.1 build 7
[05:14:43] [modloading-worker-0/INFO]: Forge mod loading, version 43.1.52, for MC 1.19.2 with MCP 20220805.130853
[05:14:43] [modloading-worker-0/INFO]: MinecraftForge v43.1.52 Initialized
[05:14:44] [Thread 5/INFO]: Connecting to Essential Connection Manager...
[05:14:44] [Essential Thread 2/INFO]: Using Default JreSocketFactory
[05:14:44] [Render thread/INFO]: Narrator library for x64 successfully loaded
[05:14:44] [Render thread/INFO]: Reloading ResourceManager: Default, Mod Resources, Essential (forge_1.19.2).jar
[05:14:44] [WebSocketConnectReadThread-81/INFO]: Opened connection to Essential ConnectionManager (code=101, message=Switching Protocols)
[05:14:44] [Essential Thread 2/INFO]: Essential Connection Manager connection established.
[05:14:45] [Forge Version Check/INFO]: [forge] Starting version check at https://files.minecraftforge.net/net/minecraftforge/forge/promotions_slim.json
[05:14:45] [ForkJoinPool.commonPool-worker-14/ERROR]: Could not find parent net/minecraft/client/renderer/texture/AbstractTexture for class gg/essential/universal/utils/ReleasedDynamicTexture in classloader jdk.internal.loader.ClassLoaders$AppClassLoader@67b64c45 on thread Thread[ForkJoinPool.commonPool-worker-14,10,main]
[05:14:45] [ForkJoinPool.commonPool-worker-14/ERROR]: An error occurred building event handler
java.lang.ClassNotFoundException: net.minecraft.client.renderer.texture.AbstractTexture
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraftforge.eventbus.EventSubclassTransformer.buildEvents(EventSubclassTransformer.java:92) ~[eventbus-6.0.3.jar:?]
	at net.minecraftforge.eventbus.EventSubclassTransformer.transform(EventSubclassTransformer.java:44) ~[eventbus-6.0.3.jar:?]
	at net.minecraftforge.eventbus.EventBusEngine.processClass(EventBusEngine.java:26) ~[eventbus-6.0.3.jar:?]
	at net.minecraftforge.eventbus.service.ModLauncherService.processClassWithFlags(ModLauncherService.java:32) ~[eventbus-6.0.3.jar:6.0.3+6.0.3+master.039e4ea9]
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-10.0.8.jar:?]
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-10.0.8.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-10.0.8.jar:?]
	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113) ~[securejarhandler-2.1.4.jar:?]
	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.4.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.1.4.jar:?]
	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.1.4.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-2.1.4.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at gg.essential.universal.UGraphics.getTexture(UGraphics.java:495) ~[?:?]
	at gg.essential.elementa.components.UIImage._init_$lambda-0(UIImage.kt:57) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) [?:?]
	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]
[05:14:45] [ForkJoinPool.commonPool-worker-8/ERROR]: Could not find parent kotlin/jvm/internal/Lambda for class gg/essential/elementa/components/UIImage$1$1 in classloader jdk.internal.loader.ClassLoaders$AppClassLoader@67b64c45 on thread Thread[ForkJoinPool.commonPool-worker-8,10,main]
[05:14:45] [ForkJoinPool.commonPool-worker-8/ERROR]: An error occurred building event handler
java.lang.ClassNotFoundException: kotlin.jvm.internal.Lambda
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraftforge.eventbus.EventSubclassTransformer.buildEvents(EventSubclassTransformer.java:92) ~[eventbus-6.0.3.jar:?]
	at net.minecraftforge.eventbus.EventSubclassTransformer.transform(EventSubclassTransformer.java:44) ~[eventbus-6.0.3.jar:?]
	at net.minecraftforge.eventbus.EventBusEngine.processClass(EventBusEngine.java:26) ~[eventbus-6.0.3.jar:?]
	at net.minecraftforge.eventbus.service.ModLauncherService.processClassWithFlags(ModLauncherService.java:32) ~[eventbus-6.0.3.jar:6.0.3+6.0.3+master.039e4ea9]
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-10.0.8.jar:?]
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-10.0.8.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-10.0.8.jar:?]
	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113) ~[securejarhandler-2.1.4.jar:?]
	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.4.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.1.4.jar:?]
	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.1.4.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-2.1.4.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at gg.essential.elementa.components.UIImage._init_$lambda-0(UIImage.kt:58) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) [?:?]
	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]
[05:14:46] [Forge Version Check/INFO]: [forge] Found status: AHEAD Current: 43.1.52 Target: null
[05:14:46] [DefaultDispatcher-worker-2/INFO]: Connected to Discord as Polyframe#6478
[05:14:46] [Render thread/WARN]: Shader 953babc61b7d3bc9bfd95a62e6dc933dc8629aeb could not find uniform named subpixel_amount in the specified shader program.
[05:14:53] [Render thread/WARN]: Missing sound for event: minecraft:item.goat_horn.play
[05:14:53] [Render thread/WARN]: Missing sound for event: minecraft:entity.goat.screaming.horn_break
[05:14:53] [Render thread/INFO]: OpenAL initialized on device OpenAL Soft on Speakers (PRO X Wireless Gaming Headset)
[05:14:53] [Render thread/INFO]: Sound engine started
[05:14:53] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/blocks.png-atlas
[05:14:53] [Render thread/INFO]: Created: 256x128x4 minecraft:textures/atlas/signs.png-atlas
[05:14:53] [Render thread/INFO]: Created: 512x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[05:14:53] [Render thread/INFO]: Created: 512x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[05:14:53] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[05:14:53] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[05:14:53] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[05:14:54] [Render thread/WARN]: Shader rendertype_entity_translucent_emissive could not find sampler named Sampler2 in the specified shader program.
[05:14:55] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
[05:14:55] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[05:14:55] [Render thread/INFO]: Created: 128x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[05:14:59] [Render thread/ERROR]: Signature is missing from textures payload
[05:15:12] [Render thread/INFO]: Loaded 7 recipes
[05:15:13] [Render thread/INFO]: Loaded 1179 advancements
[05:15:15] [Render thread/INFO]: Loaded 7 recipes
[05:15:15] [Render thread/INFO]: Loaded 1179 advancements
[05:15:23] [Render thread/ERROR]: Unable to determine primary resource pack: Mod Resources net.minecraftforge.resource.DelegatingPackResources mod_resources
[05:15:23] [Server thread/INFO]: Starting integrated minecraft server version 1.19.2
[05:15:23] [Server thread/INFO]: Generating keypair
[05:15:23] [Server thread/WARN]: Configuration file C:\Users\Court\curseforge\minecraft\Instances\B\saves\New World\serverconfig\forge-server.toml is not correct. Correcting
[05:15:23] [Server thread/WARN]: Incorrect key server was corrected from null to its default, SimpleCommentedConfig:{}. 
[05:15:23] [Server thread/WARN]: Incorrect key server.removeErroringBlockEntities was corrected from null to its default, false. 
[05:15:23] [Server thread/WARN]: Incorrect key server.removeErroringEntities was corrected from null to its default, false. 
[05:15:23] [Server thread/WARN]: Incorrect key server.fullBoundingBoxLadders was corrected from null to its default, false. 
[05:15:23] [Server thread/WARN]: Incorrect key server.zombieBaseSummonChance was corrected from null to its default, 0.1. 
[05:15:23] [Server thread/WARN]: Incorrect key server.zombieBabyChance was corrected from null to its default, 0.05. 
[05:15:23] [Server thread/WARN]: Incorrect key server.fixAdvancementLoading was corrected from null to its default, true. 
[05:15:23] [Server thread/WARN]: Incorrect key server.permissionHandler was corrected from null to its default, forge:default_handler. 
[05:15:36] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[05:15:37] [Render thread/INFO]: Preparing spawn area: 0%
[05:15:37] [Render thread/INFO]: Preparing spawn area: 0%
[05:15:37] [Render thread/INFO]: Preparing spawn area: 0%
[05:15:38] [Render thread/INFO]: Preparing spawn area: 0%
[05:15:38] [Render thread/INFO]: Preparing spawn area: 0%
[05:15:39] [Render thread/INFO]: Preparing spawn area: 0%
[05:15:39] [Render thread/INFO]: Preparing spawn area: 1%
[05:15:40] [Render thread/INFO]: Preparing spawn area: 3%
[05:15:40] [Render thread/INFO]: Preparing spawn area: 4%
[05:15:41] [Render thread/INFO]: Preparing spawn area: 6%
[05:15:41] [Render thread/INFO]: Preparing spawn area: 7%
[05:15:42] [Render thread/INFO]: Preparing spawn area: 10%
[05:15:42] [Render thread/INFO]: Preparing spawn area: 12%
[05:15:43] [Render thread/INFO]: Preparing spawn area: 15%
[05:15:43] [Render thread/INFO]: Preparing spawn area: 17%
[05:15:44] [Render thread/INFO]: Preparing spawn area: 22%
[05:15:44] [Render thread/INFO]: Preparing spawn area: 24%
[05:15:45] [Render thread/INFO]: Preparing spawn area: 27%
[05:15:45] [Render thread/INFO]: Preparing spawn area: 31%
[05:15:46] [Render thread/INFO]: Preparing spawn area: 34%
[05:15:46] [Render thread/INFO]: Preparing spawn area: 38%
[05:15:47] [Render thread/INFO]: Preparing spawn area: 41%
[05:15:47] [Render thread/INFO]: Preparing spawn area: 44%
[05:15:48] [Render thread/INFO]: Preparing spawn area: 48%
[05:15:48] [Render thread/INFO]: Preparing spawn area: 52%
[05:15:49] [Render thread/INFO]: Preparing spawn area: 55%
[05:15:49] [Render thread/INFO]: Preparing spawn area: 59%
[05:15:50] [Render thread/INFO]: Preparing spawn area: 63%
[05:15:50] [Render thread/INFO]: Preparing spawn area: 68%
[05:15:51] [Render thread/INFO]: Preparing spawn area: 71%
[05:15:51] [Render thread/INFO]: Preparing spawn area: 75%
[05:15:52] [Render thread/INFO]: Preparing spawn area: 79%
[05:15:52] [Render thread/INFO]: Preparing spawn area: 84%
[05:15:53] [Render thread/INFO]: Preparing spawn area: 86%
[05:15:53] [Render thread/INFO]: Preparing spawn area: 90%
[05:15:54] [Render thread/INFO]: Preparing spawn area: 94%
[05:15:54] [Render thread/INFO]: Preparing spawn area: 99%
[05:15:54] [Server thread/INFO]: Successfully initialized permission handler forge:default_handler
[05:15:54] [Render thread/INFO]: Time elapsed: 18035 ms
[05:15:54] [Server thread/INFO]: Changing view distance to 12, from 10
[05:15:54] [Server thread/INFO]: Changing simulation distance to 12, from 0
[05:15:55] [Render thread/WARN]: Unable to parse the boolean system property 'java.net.preferIPv6Addresses':system - using the default value: false
[05:15:55] [Netty Local Client IO #0/INFO]: Connected to a modded server.
[05:15:55] [Server thread/INFO]: Using new advancement loading for net.minecraft.server.PlayerAdvancements@245b86e5
[05:15:55] [Server thread/INFO]: PolyframeX[local:E:042074f5] logged in with entity id 59 at (-93.5, 77.0, 246.5)
[05:15:55] [Server thread/INFO]: PolyframeX joined the game
[05:15:56] [Render thread/INFO]: Loaded 0 advancements
[05:15:57] [Render thread/ERROR]: Signature is missing from textures payload
[05:15:57] [Server thread/INFO]: Saving and pausing game...
[05:15:58] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:overworld
[05:15:59] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_end
[05:15:59] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_nether
[05:15:59] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 2422ms or 48 ticks behind
[05:16:01] [Server thread/INFO]: PolyframeX lost connection: Disconnected
[05:16:01] [Server thread/INFO]: PolyframeX left the game
[05:16:01] [Server thread/INFO]: Stopping singleplayer server as player logged out
[05:16:01] [Server thread/INFO]: Stopping server
[05:16:01] [Server thread/INFO]: Saving players
[05:16:01] [Server thread/INFO]: Saving worlds
[05:16:03] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:overworld
[05:16:03] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_end
[05:16:03] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_nether
[05:16:03] [Server thread/INFO]: ThreadedAnvilChunkStorage (New World): All chunks are saved
[05:16:03] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[05:16:03] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[05:16:03] [Server thread/INFO]: ThreadedAnvilChunkStorage: All dimensions are saved
[05:16:04] [Render thread/ERROR]: Signature is missing from textures payload
[05:16:07] [Render thread/INFO]: Stopping!
[05:16:07] [DefaultDispatcher-worker-3/ERROR]: Exception caught in Discord IPC: 
java.io.IOException: Stream Closed
	at java.io.RandomAccessFile.read0(Native Method) ~[?:?]
	at java.io.RandomAccessFile.read(RandomAccessFile.java:365) ~[?:?]
	at java.io.RandomAccessFile.readInt(RandomAccessFile.java:837) ~[?:?]
	at gg.essential.lib.kdiscordipc.core.socket.impl.WindowsSocket.read(WindowsSocket.kt:38) ~[Essential%20(forge_1.19.2).jar%23155!/:?]
	at gg.essential.lib.kdiscordipc.core.socket.handler.SocketHandler$events$1.invokeSuspend(SocketHandler.kt:38) ~[Essential%20(forge_1.19.2).jar%23155!/:?]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) [kotlinforforge-3.6.0-obf.jar%23147!/:3.6.0]
	at kotlinx.coroutines.flow.internal.SafeCollector.invokeSuspend(SafeCollector.kt:48) [kotlinforforge-3.6.0-obf.jar%23147!/:3.6.0]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) [kotlinforforge-3.6.0-obf.jar%23147!/:3.6.0]
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) [kotlinforforge-3.6.0-obf.jar%23147!/:3.6.0]
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42) [kotlinforforge-3.6.0-obf.jar%23147!/:3.6.0]
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95) [kotlinforforge-3.6.0-obf.jar%23147!/:3.6.0]
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570) [kotlinforforge-3.6.0-obf.jar%23147!/:3.6.0]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749) [kotlinforforge-3.6.0-obf.jar%23147!/:3.6.0]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677) [kotlinforforge-3.6.0-obf.jar%23147!/:3.6.0]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664) [kotlinforforge-3.6.0-obf.jar%23147!/:3.6.0]

**Comment by PolyframeX** [comment]
If this helps, I am using LittleSkin API with a high res skin and cape, and the player appears like this:
![image](https://user-images.githubusercontent.com/80133652/201319626-20f52052-47e3-4207-9328-d2cd7e60bab2.png)

**Comment by xfl03** [comment]
Please provide `.minecraft/CustomSkinLoader/CustomSkinLoader.log`

**Comment by PolyframeX** [comment]
[CustomSkinLoader.log](https://github.com/xfl03/MCCustomSkinLoader/files/9993109/CustomSkinLoader.log)

**Comment by PolyframeX** [comment]
Here is the logs:

[2022-11-11 05:19:07] [Render thread INFO] CustomSkinLoader 14.14
[2022-11-11 05:19:07] [Render thread INFO] DataDir: C:\Users\Court\curseforge\minecraft\Instances\B\CustomSkinLoader
[2022-11-11 05:19:07] [Render thread INFO] Operating System: Windows 10 (amd64) version 10.0
[2022-11-11 05:19:07] [Render thread INFO] Java Version: 17.0.3, Microsoft
[2022-11-11 05:19:07] [Render thread INFO] Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
[2022-11-11 05:19:07] [Render thread INFO] Minecraft: unknown
[2022-11-11 05:19:07] [Render thread INFO] Config File: C:\Users\Court\curseforge\minecraft\Instances\B\CustomSkinLoader\CustomSkinLoader.json
[2022-11-11 05:19:07] [Render thread INFO] Try to load config.
[2022-11-11 05:19:07] [Render thread INFO] Successfully load config.
[2022-11-11 05:19:07] [Render thread INFO] Add a profile loader: MojangAPI
[2022-11-11 05:19:07] [Render thread INFO] Add a profile loader: Legacy
[2022-11-11 05:19:07] [Render thread INFO] Add a profile loader: CustomSkinAPI
[2022-11-11 05:19:07] [Render thread INFO] Add a profile loader: CustomSKinAPIPlus
[2022-11-11 05:19:07] [Render thread INFO] Add a profile loader: UniSkinAPI
[2022-11-11 05:19:07] [Render thread INFO] Add a profile loader: ElyByAPI
[2022-11-11 05:19:07] [Render thread INFO] Add a profile loader: GlitchlessAPI
[2022-11-11 05:19:07] [Render thread INFO] Add a profile loader: MinecraftCapesAPI
[2022-11-11 05:19:07] [Render thread INFO] Successfully update config.
[2022-11-11 05:19:07] [Render thread INFO] version : 14.14
[2022-11-11 05:19:07] [Render thread INFO] buildNumber : 347
[2022-11-11 05:19:07] [Render thread INFO] loadlist : [{ "name": "LittleSkin", "type": "CustomSkinAPI", "root": "https://littleskin.cn/csl/" }, { "name": "Mojang", "type": "MojangAPI", "apiRoot": "https://api.mojang.com/", "sessionRoot": "https://sessionserver.mojang.com/" }]
[2022-11-11 05:19:07] [Render thread INFO] enableDynamicSkull : true
[2022-11-11 05:19:07] [Render thread INFO] enableTransparentSkin : true
[2022-11-11 05:19:07] [Render thread INFO] forceIgnoreHttpsCertificate : false
[2022-11-11 05:19:07] [Render thread INFO] forceLoadAllTextures : false
[2022-11-11 05:19:07] [Render thread INFO] enableCape : true
[2022-11-11 05:19:07] [Render thread INFO] threadPoolSize : 1
[2022-11-11 05:19:07] [Render thread INFO] retryTime : 1
[2022-11-11 05:19:07] [Render thread INFO] cacheExpiry : 30
[2022-11-11 05:19:07] [Render thread INFO] forceUpdateSkull : false
[2022-11-11 05:19:07] [Render thread INFO] enableLocalProfileCache : false
[2022-11-11 05:19:07] [Render thread INFO] enableCacheAutoClean : false
[2022-11-11 05:19:07] [Render thread INFO] forceDisableCache : false
[2022-11-11 05:19:07] [PolyframeX INFO] Loading PolyframeX's profile.
[2022-11-11 05:19:07] [PolyframeX INFO] 1/2 Try to load profile from 'LittleSkin'.
[2022-11-11 05:19:07] [PolyframeX DEBUG] Try to request 'https://littleskin.cn/csl/PolyframeX.json'.
[2022-11-11 05:19:07] [Render thread INFO] ThreadDownloadImageData Class: net.minecraft.client.renderer.texture.HttpTexture
[2022-11-11 05:19:08] [PolyframeX DEBUG] Successfully request (Response Code: 304 , Content Length: -1)
[2022-11-11 05:19:08] [PolyframeX DEBUG] Cache file found (Length: 186 , Path: 'C:\Users\Court\curseforge\minecraft\Instances\B\CustomSkinLoader\caches\77774b9b5ddff418e60e4da4f6d41c091f640ef0' , Expire: 0)
[2022-11-11 05:19:08] [PolyframeX INFO] Try to load from cache 'C:\Users\Court\curseforge\minecraft\Instances\B\CustomSkinLoader\caches\77774b9b5ddff418e60e4da4f6d41c091f640ef0'.
[2022-11-11 05:19:08] [PolyframeX DEBUG] Successfully load from cache
[2022-11-11 05:19:08] [PolyframeX DEBUG] Content: {"username":"PolyframeX","skins":{"default":"5a6b62c7f809cfad0c93371e1c49227e8a2b876400db2337c37522e7c188fb96"},"cape":"2de854e7a02144a7a5ea409ccac263b719fb5a161ab8ec71cc9e1a680f550ab8"}
[2022-11-11 05:19:08] [PolyframeX INFO] PolyframeX's profile loaded.
[2022-11-11 05:19:08] [PolyframeX INFO] (SkinUrl: https://littleskin.cn/csl/textures/5a6b62c7f809cfad0c93371e1c49227e8a2b876400db2337c37522e7c188fb96 , Model: default , CapeUrl: https://littleskin.cn/csl/textures/2de854e7a02144a7a5ea409ccac263b719fb5a161ab8ec71cc9e1a680f550ab8  , Expiry: 1668161978)
[2022-11-11 05:19:08] [PolyframeX DEBUG] Try to request 'https://littleskin.cn/csl/textures/5a6b62c7f809cfad0c93371e1c49227e8a2b876400db2337c37522e7c188fb96'.
[2022-11-11 05:19:08] [PolyframeX DEBUG] Cache file found (Length: 2049 , Path: 'C:\Users\Court\curseforge\minecraft\Install\assets\skins\5a\5a6b62c7f809cfad0c93371e1c49227e8a2b876400db2337c37522e7c188fb96' , Expire: 0)
[2022-11-11 05:19:08] [PolyframeX DEBUG] Try to request 'https://littleskin.cn/csl/textures/2de854e7a02144a7a5ea409ccac263b719fb5a161ab8ec71cc9e1a680f550ab8'.
[2022-11-11 05:19:08] [PolyframeX DEBUG] Cache file found (Length: 764 , Path: 'C:\Users\Court\curseforge\minecraft\Install\assets\skins\2d\2de854e7a02144a7a5ea409ccac263b719fb5a161ab8ec71cc9e1a680f550ab8' , Expire: 0)
[2022-11-11 05:19:08] [Render thread DEBUG] Loading type: SKIN
[2022-11-11 05:19:08] [Render thread DEBUG] Loading type: CAPE

**Comment by PolyframeX** [comment]
I realized it would be impossible to fix this from your stand point as essential completly changes how skins load. Sorry for wasting your time.

**Comment by PolyframeX** [comment]
I am not sure why I closed this page in the first place, I should ask you if there is any possible work arounds, (maybe a diffrent loading method via configuration?)

**Comment by HowardZHY** [comment]
at least 1.8.9 works fine with ESSENTIAL

**Comment by xfl03** [comment]
Please use standard 64*64 skin when using Essential.

**Comment by PolyframeX** [comment]
Is there any way to get 128*128 skins to work? That's kinda the entire point I got this mod. (Plus the custom cape)

**Comment by xfl03** [comment]
> Is there any way to get 128*128 skins to work? That's kinda the entire point I got this mod. (Plus the custom cape)

Essential is a closed-source mod and remade the player model, so we cannot support HD skin with Essential.  
Standard 64*64 skin can work well with Essential.
