### ISSUE TITLE
添加模组后无法启动游戏

### ISSUE THREAD

**Issue by xiao-k233** [JLChnToZ/MCCustomSkinLoader#82]
我在添加模组后，无法启动游戏，客户端版本：1.12.2
java版本：jre8u232
还有其他模组
经过排除，确认是该模组引起无法启动。
![image](https://user-images.githubusercontent.com/58621432/75507112-1455b700-5a1b-11ea-802f-3a43c8e1ab22.png)

错误Log：
[11:11:58] [main/ERROR] [FML]: FML appears to be missing any signature data. This is not a good thing

[11:12:02] [main/ERROR] [mixin]: Critical problem: mixins.liteloader.client.preinit.json:MixinClientBrandRetriever target net.minecraft.client.ClientBrandRetriever was already transformed.

[11:12:28] [Client thread/INFO] [STDERR]: [net.optifine.reflect.FieldLocatorType:getField:85]: java.lang.NoClassDefFoundError: Lnet/minecraft/client/resources/SkinManager;

[11:12:28] [Client thread/INFO] [STDERR]: [net.optifine.reflect.FieldLocatorType:getField:85]: 	at java.lang.Class.getDeclaredFields0(Native Method)

[11:12:28] [Client thread/INFO] [STDERR]: [net.optifine.reflect.FieldLocatorType:getField:85]: 	at java.lang.Class.privateGetDeclaredFields(Unknown Source)

[11:12:28] [Client thread/INFO] [STDERR]: [net.optifine.reflect.FieldLocatorType:getField:85]: 	at java.lang.Class.getDeclaredFields(Unknown Source)

[11:12:28] [Client thread/INFO] [STDERR]: [net.optifine.reflect.FieldLocatorType:getField:85]: 	at net.optifine.reflect.FieldLocatorType.getField(FieldLocatorType.java:55)

[11:12:28] [Client thread/INFO] [STDERR]: [net.optifine.reflect.FieldLocatorType:getField:85]: 	at net.optifine.reflect.ReflectorField.getTargetField(ReflectorField.java:80)

[11:12:28] [Client thread/INFO] [STDERR]: [net.optifine.reflect.FieldLocatorType:getField:85]: 	at net.optifine.reflect.ReflectorField.<init>(ReflectorField.java:70)

[11:12:28] [Client thread/INFO] [STDERR]: [net.optifine.reflect.FieldLocatorType:getField:85]: 	at net.optifine.reflect.ReflectorField.<init>(ReflectorField.java:59)

[11:12:28] [Client thread/INFO] [STDERR]: [net.optifine.reflect.FieldLocatorType:getField:85]: 	at net.optifine.reflect.ReflectorField.<init>(ReflectorField.java:45)

[11:12:28] [Client thread/INFO] [STDERR]: [net.optifine.reflect.FieldLocatorType:getField:85]: 	at net.optifine.reflect.ReflectorField.<init>(ReflectorField.java:37)

[11:12:28] [Client thread/INFO] [STDERR]: [net.optifine.reflect.FieldLocatorType:getField:85]: 	at net.optifine.reflect.Reflector.<clinit>(Reflector.java:501)

[11:12:28] [Client thread/INFO] [STDERR]: [net.optifine.reflect.FieldLocatorType:getField:85]: 	at net.minecraft.client.settings.GameSettings.setForgeKeybindProperties(GameSettings.java:3452)

[11:12:28] [Client thread/INFO] [STDERR]: [net.optifine.reflect.FieldLocatorType:getField:85]: 	at net.minecraft.client.settings.GameSettings.<init>(GameSettings.java:307)

[11:12:28] [Client thread/INFO] [STDERR]: [net.optifine.reflect.FieldLocatorType:getField:85]: 	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:444)

[11:12:28] [Client thread/INFO] [STDERR]: [net.optifine.reflect.FieldLocatorType:getField:85]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:3931)

[11:12:28] [Client thread/INFO] [STDERR]: [net.optifine.reflect.FieldLocatorType:getField:85]: 	at net.minecraft.client.main.Main.main(SourceFile:123)

[11:12:28] [Client thread/INFO] [STDERR]: [net.optifine.reflect.FieldLocatorType:getField:85]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

[11:12:28] [Client thread/INFO] [STDERR]: [net.optifine.reflect.FieldLocatorType:getField:85]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)

[11:12:28] [Client thread/INFO] [STDERR]: [net.optifine.reflect.FieldLocatorType:getField:85]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)

[11:12:28] [Client thread/INFO] [STDERR]: [net.optifine.reflect.FieldLocatorType:getField:85]: 	at java.lang.reflect.Method.invoke(Unknown Source)

[11:12:28] [Client thread/INFO] [STDERR]: [net.optifine.reflect.FieldLocatorType:getField:85]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)

[11:12:28] [Client thread/INFO] [STDERR]: [net.optifine.reflect.FieldLocatorType:getField:85]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

[11:12:28] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: Caused by: java.lang.ClassNotFoundException: net.minecraft.client.resources.SkinManager

[11:12:28] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)

[11:12:28] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at java.lang.ClassLoader.loadClass(Unknown Source)

[11:12:28] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at java.lang.ClassLoader.loadClass(Unknown Source)

[11:12:28] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	... 21 more

[11:12:28] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: Caused by: java.lang.ClassFormatError: Duplicate field name "fakeManager" with signature "Lcustomskinloader.fake.FakeSkinManager;" in class file net/minecraft/client/resources/SkinManager

[11:12:28] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at java.lang.ClassLoader.defineClass1(Native Method)

[11:12:28] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at java.lang.ClassLoader.defineClass(Unknown Source)

[11:12:28] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at java.security.SecureClassLoader.defineClass(Unknown Source)

[11:12:28] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)

[11:12:28] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	... 23 more

[11:12:28] [Client thread/ERROR] [LaunchWrapper]: Unable to launch

[11:12:28] [Client thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException

[11:12:28] [Client thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)

[11:12:28] [Client thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.SecurityManager.checkExit(Unknown Source)

[11:12:28] [Client thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.Runtime.exit(Unknown Source)

[11:12:28] [Client thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.System.exit(Unknown Source)

[11:12:28] [Client thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)

[11:12:28] [Client thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

Exception in thread "Client thread" 
![image](https://user-images.githubusercontent.com/58621432/75507200-5c74d980-5a1b-11ea-9cce-ed9e9d3ea32a.png)

**Comment by xiao-k233** [comment]
客户端同时使用Forge和liteloader

**Comment by ZekerZhayard** [comment]
我感觉你同时装了两个 CustomSkinLoader
```
[11:12:28] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: Caused by: java.lang.ClassFormatError: Duplicate field name "fakeManager" with signature "Lcustomskinloader.fake.FakeSkinManager;" in class file net/minecraft/client/resources/SkinManager
```

**Comment by xfl03** [comment]
我也怀疑是装了两个CustomSkinLoader导致的，不过需要的话我可以从代码上尝试规避一下

**Comment by xfl03** [comment]
@xiao-k233 已从代码上规避这一问题，希望可以进行测试
下载：https://csl.littleservice.cn/mods/CustomSkinLoader_Forge-14.12-SNAPSHOT-111.jar

**Comment by xiao-k233** [comment]
我已解决，是原来的版本是14.10，配置文件不兼容导致。额，确实，我装了俩awa。不过删了之后还那样，所以，开头是原因所在。

**Comment by xfl03** [comment]
配置文件不会不兼容的，就是装了因为两个CustomSkinLoader
